/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mike.game.guess.animal;

import java.awt.Dimension;
import static java.lang.System.exit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mrani
 */
public class AnimalForm extends javax.swing.JFrame  {

    private QuestionAnswer qa;
    
    private final Service service = new ServiceImpl();
    /**
     * Creates new form AnimalForm
     */
    public AnimalForm() {
        initComponents();
        
        this.mainPanel.add(homePanel);
        this.mainPanel.add(gamePanel);
        this.mainPanel.add(addAnimalPanel);
        
        homePanel.setVisible(true);
        gamePanel.setVisible(false);
        addAnimalPanel.setVisible(false);
        
        List<Animal> animals = service.loadAnimals();
        animals.forEach(animal -> animalListPanel.add(new JLabel(animal.getName())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAnimalPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        animalName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        canFly = new javax.swing.JCheckBox();
        canSwim = new javax.swing.JCheckBox();
        liveInWater = new javax.swing.JCheckBox();
        aggressive = new javax.swing.JCheckBox();
        venomous = new javax.swing.JCheckBox();
        domesticated = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        animalClass = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        animalId1 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        animalId2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        headerTitle = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        questionAns = new javax.swing.JLabel();
        ansDesc = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        questionPanel = new javax.swing.JPanel();
        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        finishPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        enterAnimalPanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        animalListPanel = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        play = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        addAnimal = new javax.swing.JMenuItem();
        letsPlay = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();

        addAnimalPanel.setPreferredSize(new java.awt.Dimension(800, 650));
        addAnimalPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(567, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Add A New Animal Into the Game");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 221, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 221, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        addAnimalPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(567, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Animal: ");

        animalName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalName.setToolTipText("i.e. Lion, Tiger, etc.");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Check Exist");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(animalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Characteristics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(4, 2));

        canFly.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canFly.setText("Can Fly");
        jPanel6.add(canFly);

        canSwim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        canSwim.setText("Can Swim");
        canSwim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canSwimActionPerformed(evt);
            }
        });
        jPanel6.add(canSwim);

        liveInWater.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        liveInWater.setText("Live in the water");
        jPanel6.add(liveInWater);

        aggressive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aggressive.setText("Aggressive");
        jPanel6.add(aggressive);

        venomous.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        venomous.setText("Venomous");
        jPanel6.add(venomous);

        domesticated.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        domesticated.setText("Domesticated");
        jPanel6.add(domesticated);

        jPanel5.add(jPanel6);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unique Identifiers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(382, 200));
        jPanel10.setLayout(new java.awt.GridLayout(3, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Animal Class:");

        animalClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Mammal", "Bird", "Fish", "Reptile", "Amphibian" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalClass, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(animalClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel10.add(jPanel11);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identifier #1:");

        animalId1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalId1.setToolTipText("i.e. With yellow fur and golden mane");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalId1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(animalId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Identifier #2:");

        animalId2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        animalId2.setToolTipText("i.e. With loud roar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalId2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(animalId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel13);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel9);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        addAnimalPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(567, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        addAnimalPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        gamePanel.setPreferredSize(new java.awt.Dimension(800, 650));
        gamePanel.setLayout(new java.awt.BorderLayout());

        headerTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerTitle.setText("  Question...");
        gamePanel.add(headerTitle, java.awt.BorderLayout.PAGE_START);

        jPanel14.setLayout(new java.awt.GridLayout(2, 0));

        jPanel19.setLayout(new java.awt.GridLayout(2, 0));

        questionAns.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        questionAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionAns.setText("Can this animal fly ?");
        questionAns.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel19.add(questionAns);

        ansDesc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ansDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel19.add(ansDesc);

        jPanel14.add(jPanel19);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setPreferredSize(new java.awt.Dimension(800, 60));
        jPanel16.setLayout(new java.awt.CardLayout());

        questionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        yes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        yes.setText("Yes");
        yes.setPreferredSize(new java.awt.Dimension(100, 53));
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        questionPanel.add(yes);

        no.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        no.setText("No");
        no.setPreferredSize(new java.awt.Dimension(100, 53));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        questionPanel.add(no);

        jPanel16.add(questionPanel, "card4");

        jButton4.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jButton4.setText("Play Again !");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        finishPanel.add(jButton4);

        jPanel16.add(finishPanel, "card3");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("Add Animal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        enterAnimalPanel.add(jButton5);

        jPanel16.add(enterAnimalPanel, "card4");

        jPanel15.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel14.add(jPanel15);

        gamePanel.add(jPanel14, java.awt.BorderLayout.CENTER);

        homePanel.setPreferredSize(new java.awt.Dimension(800, 650));
        homePanel.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Guess The Animal");
        jLabel4.setPreferredSize(new java.awt.Dimension(323, 100));
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        homePanel.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel20, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel21, java.awt.BorderLayout.LINE_START);

        animalListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose one in your mind", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        animalListPanel.setLayout(new java.awt.GridLayout(5, 5, 20, 5));
        jPanel17.add(animalListPanel, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(800, 300));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        play.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        play.setText("Let's Play !");
        play.setPreferredSize(new java.awt.Dimension(300, 150));
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jPanel18.add(play, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel18, java.awt.BorderLayout.SOUTH);

        homePanel.add(jPanel8, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess The Animal");
        setPreferredSize(new java.awt.Dimension(800, 650));

        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Game");

        home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        home.setText("Home");
        home.setToolTipText("");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenu1.add(home);

        addAnimal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addAnimal.setText("Add Animal");
        addAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(addAnimal);

        letsPlay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        letsPlay.setText("Let's Play");
        letsPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letsPlayActionPerformed(evt);
            }
        });
        jMenu1.add(letsPlay);
        jMenu1.add(jSeparator1);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimalActionPerformed
        homePanel.setVisible(false);
        gamePanel.setVisible(false);
        addAnimalPanel.setVisible(true);
    }//GEN-LAST:event_addAnimalActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        qa = new QuestionAnswer();
        homePanel.setVisible(false);
        addAnimalPanel.setVisible(false);
        gamePanel.setVisible(true);
        questionPanel.setVisible(true);
        finishPanel.setVisible(false);
        enterAnimalPanel.setVisible(false);
        
        headerTitle.setText("Question...");
        ansDesc.setText("");
        
        service.getNextQuestion(qa);
        questionAns.setText(qa.getCurrQuestion());
    }//GEN-LAST:event_playActionPerformed

    private void letsPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letsPlayActionPerformed
        qa = new QuestionAnswer();
        this.playActionPerformed(evt);
    }//GEN-LAST:event_letsPlayActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        homePanel.setVisible(true);
        addAnimalPanel.setVisible(false);
        gamePanel.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void canSwimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canSwimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canSwimActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        canSwim.setSelected(false);
        canFly.setSelected(false);
        liveInWater.setSelected(false);
        aggressive.setSelected(false);
        venomous.setSelected(false);
        domesticated.setSelected(false);
        
        animalName.setText("");
        animalId1.setText("");
        animalId2.setText("");
        
        animalClass.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        List<String> uniqueChars = new ArrayList<String>();
        uniqueChars.add(animalClass.getSelectedItem().toString());
        uniqueChars.add(animalId1.getText());
        uniqueChars.add(animalId2.getText());
        
        Animal animal = new Animal();
        animal.setName(animalName.getText());
        animal.setAggressive(aggressive.isSelected());
        animal.setCanFly(canFly.isSelected());
        animal.setCanSwim(canSwim.isSelected());
        animal.setLiveInWater(liveInWater.isSelected());
        animal.setVenomous(venomous.isSelected());
        animal.setDomesticated(domesticated.isSelected());
        animal.setUniqueChars(uniqueChars);
        
        service.saveNewAnimal(animal);   
        
        msgbox(animal.getName() + " successfully save and ready to play !.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (animalName != null && !animalName.getText().equals("")){
            if (service.findAnimal(animalName.getText())){
                msgbox(animalName.getText() + " is available, please try a different animal.");
            } else {
                msgbox(animalName.getText() + " not found, you may enter this animal into the game.");
            }
        } else {
            msgbox("Please enter an animal name to continue."); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        qa.setUserAns(true);
        service.getNextQuestion(qa);
        if (qa.getFoundAnswer()){
            if (qa.getPossibleAnswers().size() == 1){
                headerTitle.setText("Finally, I got an answer...");
                questionAns.setText(qa.getAnswerText());
                ansDesc.setText(qa.getAnswerDesc());
                questionPanel.setVisible(false);
                finishPanel.setVisible(true);
                enterAnimalPanel.setVisible(false);
                return;
            }
            
            headerTitle.setText("Cannot guess your animal...");
            questionAns.setText(qa.getAnswerText());
            ansDesc.setText(qa.getAnswerDesc());
            questionPanel.setVisible(false);
            finishPanel.setVisible(false);
            enterAnimalPanel.setVisible(true);
            return;
        }
        questionAns.setText(qa.getCurrQuestion());
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        qa.setUserAns(false);
        service.getNextQuestion(qa);
        if (qa.getFoundAnswer()){
            if (qa.getPossibleAnswers().size() == 1){
                headerTitle.setText("Finally, I got an answer...");
                questionAns.setText(qa.getAnswerText());
                ansDesc.setText(qa.getAnswerDesc());
                questionPanel.setVisible(false);
                finishPanel.setVisible(true);
                enterAnimalPanel.setVisible(false);
                return;
            }
            
            headerTitle.setText("Cannot guess your animal...");
            questionAns.setText(qa.getAnswerText());
            ansDesc.setText(qa.getAnswerDesc());
            questionPanel.setVisible(false);
            finishPanel.setVisible(false);
            enterAnimalPanel.setVisible(true);
            return;
        }
        questionAns.setText(qa.getCurrQuestion());
    }//GEN-LAST:event_noActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        qa = new QuestionAnswer();
        this.playActionPerformed(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        addAnimalActionPerformed(evt);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void msgbox(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAnimal;
    private javax.swing.JPanel addAnimalPanel;
    private javax.swing.JCheckBox aggressive;
    private javax.swing.JComboBox<String> animalClass;
    private javax.swing.JTextField animalId1;
    private javax.swing.JTextField animalId2;
    private javax.swing.JPanel animalListPanel;
    private javax.swing.JTextField animalName;
    private javax.swing.JLabel ansDesc;
    private javax.swing.JCheckBox canFly;
    private javax.swing.JCheckBox canSwim;
    private javax.swing.JCheckBox domesticated;
    private javax.swing.JPanel enterAnimalPanel;
    private javax.swing.JMenuItem exit;
    private javax.swing.JPanel finishPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JMenuItem home;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem letsPlay;
    private javax.swing.JCheckBox liveInWater;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton no;
    private javax.swing.JButton play;
    private javax.swing.JLabel questionAns;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JCheckBox venomous;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
